USE [master]
ALTER DATABASE [sample] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [sample] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\sample_LogBackup_2022-10-17_20-59-43.bak' WITH NOFORMAT, NOINIT,  NAME = N'sample_LogBackup_2022-10-17_20-59-43', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [sample] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\fullsample.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 5
RESTORE LOG [sample] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\sampletlog.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [sample] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\sampletlog.trn' WITH  FILE = 2,  NOUNLOAD,  STATS = 5,  STOPAT = N'2022-10-17T20:54:55'
ALTER DATABASE [sample] SET MULTI_USER

GO


